from PyQt5 import QtCore, QtGui, QtWidgets

from gui.codeEditor import CodeEditor


class Ui_simMainWindow(object):
    def setupUi(self, simMainWindow):
        simMainWindow.setObjectName("simMainWindow")
        simMainWindow.resize(1040, 640)

        self.centralwidget = QtWidgets.QWidget(simMainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.assemblyEditor = CodeEditor(self.centralwidget)
        self.assemblyEditor.setGeometry(QtCore.QRect(30, 40, 331, 270))
        self.assemblyEditor.setObjectName("assemblyEditor")

        self.machineCodeViewer = CodeEditor(self.centralwidget)
        self.machineCodeViewer.setGeometry(QtCore.QRect(380, 40, 271, 270))
        self.machineCodeViewer.setObjectName("machineCodeViewer")

        self.registersTableWidget_1 = QtWidgets.QTableWidget(
            self.centralwidget)
        self.registersTableWidget_1.setGeometry(
            QtCore.QRect(680, 40, 320, 270))
        self.registersTableWidget_1.setWordWrap(True)
        self.registersTableWidget_1.setObjectName("registersTableWidget_1")
        self.registersTableWidget_1.setColumnCount(3)
        self.registersTableWidget_1.setRowCount(8)

        item = QtWidgets.QTableWidgetItem()
        self.registersTableWidget_1.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.registersTableWidget_1.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.registersTableWidget_1.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.registersTableWidget_1.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.registersTableWidget_1.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.registersTableWidget_1.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.registersTableWidget_1.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.registersTableWidget_1.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setUnderline(True)
        item.setFont(font)
        self.registersTableWidget_1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setUnderline(True)
        item.setFont(font)
        self.registersTableWidget_1.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setUnderline(True)
        item.setFont(font)
        self.registersTableWidget_1.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.registersTableWidget_1.horizontalHeader().setDefaultSectionSize(90)
        self.registersTableWidget_1.horizontalHeader().setMinimumSectionSize(90)
        self.registersTableWidget_1.horizontalHeader().setStretchLastSection(True)
        self.registersTableWidget_1.verticalHeader().setCascadingSectionResizes(False)
        self.registersTableWidget_1.verticalHeader().setDefaultSectionSize(30)
        self.registersTableWidget_1.verticalHeader().setMinimumSectionSize(25)
        self.registersTableWidget_1.verticalHeader().setStretchLastSection(True)
        self.registersTableWidget_1.setEditTriggers(
            QtWidgets.QAbstractItemView.NoEditTriggers)

        self.runButton = QtWidgets.QToolButton(self.centralwidget)
        self.runButton.setGeometry(QtCore.QRect(30, 10, 25, 25))
        self.runButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./gui/icons/run_icon.png"),
                       QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.runButton.setIcon(icon)
        self.runButton.setIconSize(QtCore.QSize(30, 30))
        self.runButton.setObjectName("runButton")

        self.editorButtonGroup = QtWidgets.QButtonGroup(simMainWindow)
        self.editorButtonGroup.setObjectName("editorButtonGroup")
        self.editorButtonGroup.addButton(self.runButton)

        self.memoryTableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.memoryTableWidget.setGeometry(QtCore.QRect(30, 340, 970, 113))
        self.memoryTableWidget.setObjectName("memoryTableWidget")
        self.memoryTableWidget.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.memoryTableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.memoryTableWidget.setVerticalHeaderItem(1, item)
        self.memoryTableWidget.horizontalHeader().setDefaultSectionSize(90)
        self.memoryTableWidget.horizontalHeader().setMinimumSectionSize(90)
        self.memoryTableWidget.verticalHeader().setDefaultSectionSize(31)
        self.memoryTableWidget.verticalHeader().setMinimumSectionSize(31)
        self.memoryTableWidget.setEditTriggers(
            QtWidgets.QAbstractItemView.NoEditTriggers)

        self.stackTableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.stackTableWidget.setGeometry(QtCore.QRect(30, 480, 970, 113))
        self.stackTableWidget.setObjectName("stackTableWidget")
        self.stackTableWidget.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.stackTableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.stackTableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.stackTableWidget.horizontalHeader().setDefaultSectionSize(90)
        self.stackTableWidget.horizontalHeader().setMinimumSectionSize(90)
        self.stackTableWidget.verticalHeader().setDefaultSectionSize(31)
        self.stackTableWidget.verticalHeader().setMinimumSectionSize(31)
        self.stackTableWidget.setEditTriggers(
            QtWidgets.QAbstractItemView.NoEditTriggers)

        self.machineCodeLabel = QtWidgets.QLabel(self.centralwidget)
        self.machineCodeLabel.setGeometry(QtCore.QRect(380, 10, 271, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.machineCodeLabel.setFont(font)
        self.machineCodeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.machineCodeLabel.setObjectName("machineCodeLabel")

        self.stopButton = QtWidgets.QToolButton(self.centralwidget)
        self.stopButton.setGeometry(QtCore.QRect(150, 10, 25, 25))
        self.stopButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.stopButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./gui/icons/stop_icon.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stopButton.setIcon(icon1)
        self.stopButton.setIconSize(QtCore.QSize(30, 30))
        self.stopButton.setObjectName("stopButton")
        self.editorButtonGroup.addButton(self.stopButton)

        self.pauseButton = QtWidgets.QToolButton(self.centralwidget)
        self.pauseButton.setGeometry(QtCore.QRect(110, 10, 25, 25))
        self.pauseButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pauseButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("./gui/icons/pause_icon.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pauseButton.setIcon(icon2)
        self.pauseButton.setIconSize(QtCore.QSize(30, 30))
        self.pauseButton.setObjectName("pauseButton")
        self.editorButtonGroup.addButton(self.pauseButton)

        self.previousButton = QtWidgets.QToolButton(self.centralwidget)
        self.previousButton.setGeometry(QtCore.QRect(190, 10, 25, 25))
        self.previousButton.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.previousButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("./gui/icons/prev_icon.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.previousButton.setIcon(icon3)
        self.previousButton.setIconSize(QtCore.QSize(30, 30))
        self.previousButton.setObjectName("previousButton")
        self.editorButtonGroup.addButton(self.previousButton)

        self.nextButton = QtWidgets.QToolButton(self.centralwidget)
        self.nextButton.setGeometry(QtCore.QRect(230, 10, 25, 25))
        self.nextButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.nextButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("./gui/icons/next_icon.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nextButton.setIcon(icon4)
        self.nextButton.setIconSize(QtCore.QSize(30, 30))
        self.nextButton.setObjectName("nextButton")
        self.editorButtonGroup.addButton(self.nextButton)

        self.debugButton = QtWidgets.QToolButton(self.centralwidget)
        self.debugButton.setGeometry(QtCore.QRect(70, 10, 25, 25))
        self.debugButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.debugButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("./gui/icons/debug_icon.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.debugButton.setIcon(icon5)
        self.debugButton.setIconSize(QtCore.QSize(30, 30))
        self.debugButton.setObjectName("debugButton")

        self.delayLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.delayLineEdit.setGeometry(QtCore.QRect(320, 10, 41, 22))
        self.delayLineEdit.setObjectName("delayLineEdit")
        self.delayLineEdit.setPlaceholderText("1.0")
        self.delayLineEdit.setAlignment(QtCore.Qt.AlignRight)
        self.delayLabel = QtWidgets.QLabel(self.centralwidget)
        self.delayLabel.setGeometry(QtCore.QRect(270, 10, 51, 20))
        self.delayLabel.setObjectName("delayLabel")

        self.memoryLabel = QtWidgets.QLabel(self.centralwidget)
        self.memoryLabel.setGeometry(QtCore.QRect(30, 320, 61, 20))
        self.memoryLabel.setObjectName("memoryLabel")

        self.registersLabel = QtWidgets.QLabel(self.centralwidget)
        self.registersLabel.setGeometry(QtCore.QRect(714, 10, 321, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.registersLabel.setFont(font)
        self.registersLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.registersLabel.setObjectName("registersLabel")

        self.stackLabel = QtWidgets.QLabel(self.centralwidget)
        self.stackLabel.setGeometry(QtCore.QRect(30, 460, 55, 16))
        self.stackLabel.setObjectName("stackLabel")
        simMainWindow.setCentralWidget(self.centralwidget)

        self.menuBar = QtWidgets.QMenuBar(simMainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1401, 26))
        self.menuBar.setObjectName("menuBar")

        self.menufile = QtWidgets.QMenu(self.menuBar)
        self.menufile.setObjectName("menufile")
        simMainWindow.setMenuBar(self.menuBar)
        self.actionOpen_File = QtWidgets.QAction(simMainWindow)
        self.actionOpen_File.setObjectName("actionOpen_File")
        self.menufile.addAction(self.actionOpen_File)
        self.menuBar.addAction(self.menufile.menuAction())

        self.retranslateUi(simMainWindow)
        QtCore.QMetaObject.connectSlotsByName(simMainWindow)

    def retranslateUi(self, simMainWindow):
        _translate = QtCore.QCoreApplication.translate
        simMainWindow.setWindowTitle(
            _translate("simMainWindow", "MIPS Simulator"))
        item = self.registersTableWidget_1.verticalHeaderItem(0)
        item.setText(_translate("simMainWindow", "r0"))
        item = self.registersTableWidget_1.verticalHeaderItem(1)
        item.setText(_translate("simMainWindow", "r1"))
        item = self.registersTableWidget_1.verticalHeaderItem(2)
        item.setText(_translate("simMainWindow", "r2"))
        item = self.registersTableWidget_1.verticalHeaderItem(3)
        item.setText(_translate("simMainWindow", "r3"))
        item = self.registersTableWidget_1.verticalHeaderItem(4)
        item.setText(_translate("simMainWindow", "r4"))
        item = self.registersTableWidget_1.verticalHeaderItem(5)
        item.setText(_translate("simMainWindow", "ra"))
        item = self.registersTableWidget_1.verticalHeaderItem(6)
        item.setText(_translate("simMainWindow", "sp"))
        item = self.registersTableWidget_1.verticalHeaderItem(7)
        item.setText(_translate("simMainWindow", "rd"))
        item = self.registersTableWidget_1.horizontalHeaderItem(0)
        item.setText(_translate("simMainWindow", "Hex"))
        item = self.registersTableWidget_1.horizontalHeaderItem(1)
        item.setText(_translate("simMainWindow", "Signed dec"))
        item = self.registersTableWidget_1.horizontalHeaderItem(2)
        item.setText(_translate("simMainWindow", "Unsigned dec"))
        __sortingEnabled = self.registersTableWidget_1.isSortingEnabled()
        self.registersTableWidget_1.setSortingEnabled(False)
        self.runButton.setToolTip(_translate("simMainWindow", "Run"))
        item = self.memoryTableWidget.verticalHeaderItem(0)
        item.setText(_translate("simMainWindow", "Decimal"))
        item = self.memoryTableWidget.verticalHeaderItem(1)
        item.setText(_translate("simMainWindow", "Binary"))
        __sortingEnabled = self.memoryTableWidget.isSortingEnabled()
        self.memoryTableWidget.setSortingEnabled(False)
        self.memoryTableWidget.setSortingEnabled(__sortingEnabled)
        item = self.stackTableWidget.verticalHeaderItem(0)
        item.setText(_translate("simMainWindow", "Decimal"))
        item = self.stackTableWidget.verticalHeaderItem(1)
        item.setText(_translate("simMainWindow", "Binary"))
        item = self.stackTableWidget.horizontalHeaderItem(0)
        __sortingEnabled = self.stackTableWidget.isSortingEnabled()
        self.stackTableWidget.setSortingEnabled(False)
        self.stackTableWidget.setSortingEnabled(__sortingEnabled)
        self.machineCodeLabel.setText(
            _translate("simMainWindow", "Machine Code"))
        self.stopButton.setToolTip(_translate("simMainWindow", "Stop"))
        self.pauseButton.setToolTip(_translate("simMainWindow", "Pause"))
        self.previousButton.setToolTip(_translate("simMainWindow", "Previous"))
        self.nextButton.setToolTip(_translate("simMainWindow", "Next"))
        self.debugButton.setToolTip(_translate("simMainWindow", "Debug"))
        self.delayLabel.setText(_translate("simMainWindow", "Delay(s)"))
        self.memoryLabel.setText(_translate("simMainWindow", " Memory"))
        self.registersLabel.setText(_translate("simMainWindow", "Registers"))
        self.stackLabel.setText(_translate("simMainWindow", " Stack"))
        self.menufile.setTitle(_translate("simMainWindow", "File"))
        self.actionOpen_File.setText(_translate("simMainWindow", "Open File"))
